### ISSUE TITLE
JSON Syntax Error 

### ISSUE THREAD

**Issue by biscuitroller** [marcoXbresciani/TKCompanionApp#13]
Received an error in version 2.2.0 after tapping on the PDSA Journal. <br>
> Invalid PDSA Found
SyntaxError: JSON Parse error: Unexpected identifier "settings".

![Screenshot_20220622-074133](https://user-images.githubusercontent.com/51770235/175032640-0bb3ffc7-d482-4b5e-8974-f0b772577f33.png)

**Comment by marcoXbresciani** [comment]
Thank you @biscuitroller.
Yep, I think I've forgot to check days structure on first load of the JSON file used to save this PDSA test/sample page: if it's not present, it gives back this error.

Could you please confirm if the error is only on first time opening or always?

**Comment by marcoXbresciani** [comment]
Basically the error was due to the fact than when the app is trying to load the current PDSA draft for the first time, there are no data, and it is not able to convert them in the proper structure to be shown on the UI. But it's normal: if you open the app for the first time, you shall have no data.
Actually I shouldn't have left the error alert there at all! It was a tool I've used for experimenting while loading data... 👎 

Thanks for the improvement @biscuitroller . Going to fix it with next release.
